spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ssm?characterEncoding=utf8&useSSL=false&serverTimezone=UTC
    username: root
    password: 123456
mybatis:
  type-aliases-package: com.yangqihang.mapper
  mapper-locations: classpath:mybatis/mapper/*.xml