spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ssm?serverTimezone=UTC&allowMultiQueries=true
    username: root
    password: 123456
  resources:
    static-locations: classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/,file:d:/github/java_study/uploads/
mybatis:
  mapper-locations: classpath:mybatis/mapper/*.xml
  type-aliases-package: com.yangqihang.entity
logging:
  level:
    com:
      yangqihang:
        mapper: debug