spring:
  application:
    name: dubbo-demo
dubbo:
  scan:
    base-packages: com.yangqihang.service
  protocol:
    name: dubbo
    host: 192.168.1.3
    port: 666
  registry:
    address: zookeeper://192.168.74.61:2181
server:
  port: 8081