spring:
  application:
    name: dubbo-oa-provider
  datasource:
    url: jdbc:mysql://localhost:3306/ssm?serverTimezone=UTC&allowMultiQueries=true
    username: root
    password: 123456
mybatis:
  mapper-locations: classpath:mybatis/mapper/*.xml
  type-aliases-package: com.yangqihang.entity
dubbo:
  scan:
    base-packages: com.yangqihang.service
  protocol:
    name: dubbo
    host: 192.168.1.3
    port: 666
  registry:
    address: zookeeper://192.168.74.61:2181
server:
  port: 8081
